# This is a basic workflow to help you get started with Actions

name: Build And Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: ["14"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a single command using the runners shell
      - name: Install Dependencies And Build
        run: |
          npm run build

      # Runs a single command using the runners shell
      - name: Test
        run: |
          npm run test

      # Runs a set of commands using the runners shell
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          directory: components/form/coverage/
          files: ./clover.xml # optional
          flags: unittests # optional
          name: rhc-form # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      # Runs a set of commands using the runners shell
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # 目标分支
          target_branch: gh-pages
          build_dir: site/dist
          commit_message: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
